name: Security Scan

on: [pull_request]

jobs:
  fraudapi-pre-commit:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv
        working-directory: ./fraudapi

      - name: Install dependencies
        run: uv sync --group dev
        working-directory: ./fraudapi

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
        working-directory: ./fraudapi
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}